### ISSUE TITLE
TODO File

### ISSUE THREAD

**Issue by Karkus476** [SuperTux/flexlay#2]
Can be found at flexlay/supertux/TODO :
# ToDo:
- [ ] smooth selection
- [ ] **tile editor**
- [ ] **wrapper sexpr parser into a read class, LispReader like**
- [x] scrollbar in tileselector
- [x] gui and some magic to set the supertux datadir
- [ ] support additional layers (paralax and normal)
- [ ] doors/sector support needs improvement
- [ ] moving platforms + path
- [ ] camera path 
- [ ] automatic backup of files
- [ ] **get rid of make_metadat, get_ruby_object in SuperTux code**
- [ ] faster tile-loading (load on demand, pixelbuffer cache)
- [ ] **make controlpoints unzoomable**
- [ ] fix load/save and write a few testcases for them
- [ ] seperate undoable functions from not undoable ones
- [ ] provide feature to group/suspend undo/redo
- [ ] objects need to have visible text-labels attached to them (name of spawnpoints, etc.)
- [ ] all pseudo object without position (background, particle-system) should be placed beside each other beginning at 0, -32. (Currently they're all placed at 0,0)
# Bugs
- switching to the current sector resets visible properties
- sometime the tilemap is alot huger than the level

**Comment by Karkus476** [comment]
@Grumbel Why did you want the config file to be s-expr based?

**Comment by Grumbel** [comment]
That TODO is quite out of date, as some points are for the old C++/Ruby editor, not the new Python one.
- turn proc{} into blocks
- get rid of `mysprite`
- get rid of make_metadat, get_ruby_object in SuperTux code
- sexpr based config file, no evil eval games

Those are all obsolete. Config parsing using the Python configparser module and that's fine the way it is, no need for s-expr.

**Comment by Karkus476** [comment]
Edit - Removed now irrelevant entries
